Repository DoodlePlay/Frontend, pull requests merged in 2024-10, with the labels that each got.

#19 [FEAT] 대기실 페이지 개발 (socket 기능 제외) #13
  .vscode/settings.json
  firebase.js
  package-lock.json
  package.json
  public/images/lobby/checked.svg
  public/images/lobby/item.svg
  public/images/lobby/players.svg
  public/images/lobby/playing.svg
  public/images/lobby/privateRoom.svg
  public/images/lobby/publicRoom.svg
  public/images/lobby/refresh.svg
  public/images/lobby/rounds.svg
  public/images/lobby/search.svg
  public/images/lobby/selectArrow.svg
  public/images/lobby/topic.svg
  public/images/lobby/unchecked.svg
  public/images/lobby/waiting.svg
  src/app/room/page.tsx
  src/components/Button/Button.tsx
  src/components/Modal/Modal.tsx
  src/features/lobby/api/gameRoomsApi.ts
  src/features/lobby/components/CreateRoomButton.tsx
  src/features/lobby/components/CreateRoomModal.tsx
  src/features/lobby/components/GameStatusModal.tsx
  src/features/lobby/components/RefreshButton.tsx
  src/features/lobby/components/RoomCard.tsx
  src/features/lobby/components/RoomSearchSection.tsx
  src/features/lobby/components/SearchBar.tsx
  src/features/profile/components/Nickname.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#18 [FEAT] 게임방 페이지 뷰 및 이름표, 말풍선 디테일 및 테스트 코드 추가 작업 #8
  package-lock.json
  package.json
  public/images/defaultCursor.png
  public/images/drawing/breakTime.png
  public/images/drawing/breakTime.webp
  public/images/drawing/hourglass.svg
  public/images/drawing/inactiveCross.png
  public/images/drawing/items/growingBomb.png
  public/images/drawing/items/laundryFlip.png
  public/images/drawing/items/phantomReverse.png
  public/images/drawing/items/timeCutter.png
  public/images/drawing/items/toxicCover.png
  public/images/drawing/settingIcon.png
  public/images/drawing/success.png
  public/images/drawing/success.webp
  public/images/drawing/timeOver.png
  public/images/drawing/timeOver.webp
  public/images/drawing/toolbarController.svg
  public/images/drawing/waiting.png
  public/images/drawing/waiting.webp
  public/images/drawingCursor.png
  public/images/eraser.png
  src/app/game/page.tsx
  src/app/layout.tsx
  src/components/Modal/Modal.tsx
  src/components/NamePlate/NamePlate.test.tsx
  src/components/NamePlate/NamePlate.tsx
  src/components/SpeechBubble/SpeechBubble.test.tsx
  src/components/SpeechBubble/SpeechBubble.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/drawing/components/ItemBox.tsx
  src/features/drawing/components/TimeBar.tsx
  src/features/drawing/components/Toolbar.tsx
  src/features/profile/components/Nickname.tsx
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css

#22 [FIX] 파일명 및 key 값 변경 #21
  src/features/drawing/components/Drawing.tsx
Labels: 🐞 BugFix, 🎨 Html&css

#24 [FEAT]게임 진행, 대기 중 화상채팅 컴포넌트 개발 #17
  src/app/game/page.tsx
  src/app/room/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/NamePlate/NamePlate.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/features/lobby/components/UserProfileSection.tsx
  src/features/profile/components/Nickname.tsx
  src/features/videoChat/components/PlayingVideoChat.tsx
  src/features/videoChat/components/VideoChat.tsx
  src/features/videoChat/components/WaitingVideoChat.tsx
  src/hooks/Resize/Resize.test.ts
  src/hooks/Resize/Resize.ts
  src/hooks/useForm/useForm.ts
Labels: ✨ Feature, 🎨 Html&css, ✅ Test

#25 [FEAT] 채팅영역 작업 및 대기실 페이지 Socket.IO 연동 #20
  package-lock.json
  package.json
  src/app/game/page.tsx
  src/features/chat/components/Chat.tsx
  src/features/chat/components/ChatBox.tsx
  src/features/chat/components/ChatBubble.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/lobby/components/CreateRoomModal.tsx
  src/features/lobby/components/RoomSearchSection.tsx
  src/features/socket/socketStore.ts
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#27 [FEAT] 아이템 사용 시 화면 효과 제작 #23
  public/images/drawing/items/effects/explosion01.svg
  public/images/drawing/items/effects/explosion02.svg
  public/images/drawing/items/effects/toxic01.svg
  public/images/drawing/items/effects/toxic02.svg
  public/images/drawing/items/effects/toxic03.svg
  public/images/drawing/items/effects/toxic04.svg
  public/images/drawing/items/effects/toxic05.svg
  public/images/drawing/items/effects/toxic06.svg
  public/images/drawing/items/effects/toxic07.svg
  src/app/game/page.tsx
  src/components/KeywordPlate/KeywordPlate.test.tsx
  src/components/KeywordPlate/KeywordPlate.tsx
  src/components/NamePlate/NamePlate.tsx
  src/features/drawing/components/BombEffect.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/drawing/components/ItemBox.tsx
  src/features/drawing/components/TimeBar.tsx
  src/features/drawing/components/Toolbar.tsx
  src/features/drawing/components/ToxicEffect.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🎨 Html&css

#29 [FEAT] 실시간 그림 전송 및 표시 기능 구현 #28
  package-lock.json
  package.json
  src/features/drawing/components/Drawing.tsx
Labels: ✨ Feature, 🔨 Refactor

#32 [FEAT] 대기실 및 게임방 추가 작업 #30
  src/app/game/page.tsx
  src/app/room/page.tsx
  src/features/chat/components/ChatBox.tsx
  src/features/chat/components/ChatBubble.tsx
  src/features/lobby/components/CreateRoomModal.tsx
  src/features/lobby/components/RoomSearchSection.tsx
  src/features/socket/socketStore.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css

#34 [FIX] isItemsEnabled 옵셔널 체이닝 추가 #33
  src/app/game/page.tsx
Labels: 🐞 BugFix

#37 [FEAT] 아이템 사용 소켓 작업 #35
  .vscode/settings.json
  src/app/game/page.tsx
  src/features/drawing/components/BombEffect.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/ItemBox.tsx
  src/features/drawing/store/useItemStore.ts
  src/features/socket/socketStore.ts
Labels: 📬 API, ✨ Feature

#38 [FEAT] 게임 진행 우선 소켓 작업 #31
  src/components/KeywordPlate/KeywordPlate.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/lobby/api/gameRoomsApi.ts
Labels: ✨ Feature

#40 [FEAT] 게임 진행 소켓 작업 #39
  src/app/game/page.tsx
  src/components/GameStatusModal/GameStatusModal.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/lobby/api/gameRoomsApi.ts
  src/features/lobby/components/RoomSearchSection.tsx
  src/features/socket/socketStore.ts
Labels: ✨ Feature, 🔨 Refactor

#42 [FEAT] 아이템 사용 소켓 추가 작업 #41
  src/features/chat/components/ChatBox.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/drawing/components/ItemBox.tsx
  src/features/drawing/components/TimeBar.tsx
  src/features/drawing/components/ToxicEffect.tsx
  src/features/drawing/store/useItemStore.ts
  src/features/socket/socketStore.ts
Labels: 🐞 BugFix, ✨ Feature

#43 [FEAT] 정답 처리 소켓 연동 작업 #36
  src/app/game/page.tsx
  src/components/Avatar/Avatar.tsx
  src/components/NamePlate/NamePlate.tsx
  src/features/chat/components/ChatBox.tsx
  src/features/chat/components/ChatBubble.tsx
  src/features/drawing/components/Drawing.tsx
  src/features/videoChat/components/PlayingVideoChat.tsx
  src/features/videoChat/components/VideoChat.tsx
  src/features/videoChat/components/WaitingVideoChat.tsx
Labels: ✨ Feature, 🎨 Html&css
