Repository DoodlePlay/Frontend, pull requests merged in 2024-11, with the labels that each got.

#45 [FEAT] 게임 오버 상황 추가 리팩토링 #44
  public/images/drawing/gameOver.png
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/socket/socketStore.ts
Labels: 🐞 BugFix, 🔨 Refactor

#50 [FEAT] 아이템 시스템 메세지 전송 및 대기실 추가 작업 #46
  public/sounds/errorMessageSound.wav
  public/sounds/modalCancel.wav
  public/sounds/refreshButtonClick.wav
  public/sounds/roomClick.wav
  public/sounds/roomModalClick.mp3
  public/sounds/toggleButtonSound.mp3
  src/components/Button/Button.tsx
  src/components/Modal/Modal.tsx
  src/features/chat/components/ChatBox.tsx
  src/features/chat/components/ChatBubble.tsx
  src/features/lobby/components/CreateRoomButton.tsx
  src/features/lobby/components/CreateRoomModal.tsx
  src/features/lobby/components/RefreshButton.tsx
  src/features/lobby/components/RoomSearchSection.tsx
  src/features/profile/components/Nickname.tsx
  src/features/profile/store/userInfoStore.ts
  src/features/videoChat/components/PlayingVideoChat.tsx
  src/utils/helpers/playSound.ts
Labels: ✨ Feature, 🎨 Html&css

#51 [FEAT] 게임방 애니메이션 및 효과음 작업 #47
  public/sounds/bombEffect.mp3
  public/sounds/fiveSecondSound.mp3
  public/sounds/laundryEffect.mp3
  public/sounds/negativeBeeps.mp3
  public/sounds/reverseEffect.mp3
  public/sounds/selectPop.mp3
  public/sounds/timeCutterEffect.mp3
  public/sounds/toxicEffect.mp3
  src/features/drawing/components/Drawing.tsx
  src/features/drawing/components/GameControlButtons.tsx
  src/features/drawing/components/ItemBox.tsx
  src/features/drawing/components/Toolbar.tsx
  src/utils/helpers/playSound.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor
